version: "3.9"
services:
  server:
    container_name: server 
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    restart: unless-stopped
    environment:
      - ISSUER_OOBI=${ISSUER_OOBI}
      - ISSUER_PRE=${ISSUER_PRE}
      - ISSUER_REGK=${ISSUER_REGK}
      - KERIA_ENDPOINT=${KERIA_ENDPOINT:-http://keria:3901}
      - KERIA_BOOT_ENDPOINT=${KERIA_BOOT_ENDPOINT:-http://keria:3903}
    ports:
      - 3000:3000
    volumes:
      - server-data:/app/data

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
    restart: unless-stopped
    environment:
      - VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL:-http://localhost:3000}
    ports:
      - 5173:80
    
volumes:
  server-data:
